---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 13.8.5

verifier:
  name: inspec

platforms:
  - name: centos-7.4-server1
    run_list:
      - recipe[cb_prometheus::default]
      - recipe[cb_prometheus::server]
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      network:
        - ['private_network', {ip: '192.168.54.10'}]
      memory: 1024
      cpus: 1

  - name: centos-7.4-node1
    run_list:
      - recipe[cb_prometheus::default]
      - recipe[cb_prometheus::host]
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      network:
        - ['private_network', {ip: '192.168.54.21'}]
      memory: 1024
      cpus: 1

  - name: centos-7.4-node2
    run_list:
      - recipe[cb_prometheus::default]
      - recipe[cb_prometheus::minion]
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      network:
        - ['private_network', {ip: '192.168.54.22'}]
      memory: 1024
      cpus: 1

  - name: centos-7.4-node3
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      network:
        - ['private_network', {ip: '192.168.54.23'}]
      memory: 1024
      cpus: 1

  - name: centos-7.4-node4
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      network:
        - ['private_network', {ip: '192.168.54.24'}]
      memory: 1024
      cpus: 1

  - name: centos-7.4-node5
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.4
      network:
        - ['private_network', {ip: '192.168.54.25'}]
      memory: 1024
      cpus: 1

suites:
  - name: default
    run_list:
      - recipe[cb_prometheus::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
